NPCs will no longer target entities in no target
ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base pull request #1
Opened 2021-02-16 02:58 UTC by jellyton69

2021-02-16 14:32 UTC, ShadowBonnieRUS requested changes
Few changes needed.

2021-02-16 14:32 UTC, ShadowBonnieRUS commented on sb_advanced_nextbots/lua/entities/sb_advanced_nextbot_base/enemy.lua
> +	if ent:IsPlayer() and ent:IsFlagSet(FL_NOTARGET) then return false end
No `ent:IsPlayer()` check is needed, `ent:IsFlagSet` can be used on any entity. Also, it will fully match the request title.

2021-02-16 21:01 UTC, jellyton69 reviewed
All fixed.

2021-02-17 13:32 UTC, ShadowBonnieRUS approved these changes
It's okay now.

2021-02-17 13:33 UTC, merged