Length of created sequence for issequence
ShadowBonnieRUS/GMOD-SB_Advanced_Nextbots_Base pull request #11
Opened 2021-07-04 20:38 UTC by Heyter

2021-08-04 18:07 UTC, ShadowBonnieRUS commented
Если второй аргумент `true`, то первый аргумент обозначает анимацию, а не акт, но при этом анимация может быть как числом, так и строкой. Ваш фикс не учитывает этого и подходит только при вводе строки.

Однако я учел основную проблему.

2021-08-04 18:16 UTC, ShadowBonnieRUS requested changes
Некоторые замечания.

2021-08-04 18:16 UTC, ShadowBonnieRUS commented on sb_advanced_nextbots/lua/entities/sb_advanced_nextbot_base/motion.lua
> +	if issequence then
Не учтено, что `act` (и соответственно `seq` при `issequence = true`) может быть числом.

2021-08-04 18:16 UTC, ShadowBonnieRUS commented on sb_advanced_nextbots/lua/entities/sb_advanced_nextbot_base/motion.lua
> +		return select(2, self:LookupSequence(seq))
Было бы желательно отказаться от вызова двух функций сразу, вместо этого можно поместить результат выполнения основной функции `LookupSequence` в две переменные и возвратить нужную из них.

2021-08-05 14:22 UTC, Heyter commented on sb_advanced_nextbots/lua/entities/sb_advanced_nextbot_base/motion.lua
> +		return select(2, self:LookupSequence(seq))
Я закрою pull, сделаешь как лучше.

2021-08-05 14:22 UTC, closed without merging